### ISSUE TITLE
Working with data

### ISSUE THREAD

**Issue by M1HNE41** [tewarid/uwp-bluetooth-serial-tool#5] opened 2023-03-10 08:34 UTC
I am working on a project with HC-05. I can receive the data on the terminal from the bluetooth but I also need to work with it, for example if it receives 1, to do something. Is it possible to work with the data received?

**Comment by tewarid** [comment] 2023-03-10 12:29
> I am working on a project with HC-05.

Nice - HC-05 looks like an interesting little module!

> I can receive the data on the terminal from the bluetooth

Good to hear the app works as intended.

>  but I also need to work with it, for example if it receives 1, to do something. Is it possible to work with the data received?

Not really - and I don't plan on adding that feature but will not mind if someone forks the app.

**Comment by M1HNE41** [comment] 2023-03-10 17:14
then can you tell me where the transmitted data is displayed, so that I can edit it?

**Comment by tewarid** [comment] 2023-03-10 23:08
Please see

https://github.com/tewarid/uwp-bluetooth-serial-tool/blob/29126486cc820843277cc066458d3d3abdc524f0/UwpBluetoothSerialTool/Views/MainPage.xaml.cs#L310

**Comment by tewarid** [comment] 2023-03-14 12:59
Closing this issue now. Please reopen if needed.

**Closed as completed by tewarid** 2023-03-14 12:59 UTC
